SET AUTOCOMMIT = 0;

/* *********************************************************/
/* 1.- Sentencias de borrado de todas las tablas y vistas */
/* *********************************************************/
/*
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE SOCIO CASCADE CONSTRAINTS;
DROP TABLE TARIFA CASCADE CONSTRAINTS;
DROP TABLE JUEGO CASCADE CONSTRAINTS;
DROP TABLE TARIFA CASCADE CONSTRAINTS;
DROP TABLE ALQUILA CASCADE CONSTRAINTS;
DROP TABLE COMPRA CASCADE CONSTRAINTS;
DROP TABLE ASOCIADO CASCADE CONSTRAINTS;*/

/* *************************************************/
/* 2.- Creamos las tablas de nuestro Diagrama EER */
/* *************************************************/

CREATE TABLE ADMIN
(
 LOGIN_ADMIN VARCHAR2 (15) NOT NULL,
 PASS_ADMIN VARCHAR2 (20) NOT NULL,
 PRIMARY KEY(LOGIN_ADMIN)
);
CREATE TABLE VENDEDOR
(
 LOGIN_VENDEDOR VARCHAR2 (15) NOT NULL,
 PASS_VENDEDOR VARCHAR2 (20) NOT NULL,
 DNI_VENDEDOR VARCHAR2 (9) NOT NULL UNIQUE,
 NSS_VENDEDOR VARCHAR2 (11) NOT NULL UNIQUE,
 NOMBRE_VENDEDOR VARCHAR2 (25) NOT NULL,
 APELLIDOS_VENDEDOR VARCHAR2 (50) NOT NULL,
 EMAIL_VENDEDOR VARCHAR2 (60) NOT NULL,
 TELEFONO_VENDEDOR NUMBER (12) NOT NULL,
 LOGIN_ADMIN VARCHAR2 (15) NOT NULL,
 PRIMARY KEY (LOGIN_VENDEDOR),
 FOREIGN KEY (LOGIN_ADMIN) REFERENCES ADMIN ON DELETE CASCADE
);
CREATE TABLE SOCIO 
(
 LOGIN_SOCIO VARCHAR2 (15) NOT NULL,
 PASS_SOCIO VARCHAR2 (20) NOT NULL,
 DNI_VENDEDOR VARCHAR2 (9) NOT NULL UNIQUE,
 NOMBRE_SOCIO VARCHAR2 (25) NOT NULL,
 APELLIDOS_SOCIO VARCHAR2 (50) NOT NULL,
 EMAIL_VENDEDOR VARCHAR2 (60) NOT NULL,
 TELEFONO_VENDEDOR NUMBER (12) NOT NULL,
 SOCIO_BLOQUEADO BOOLEAN,
 LOGIN_VENDEDOR VARCHAR2 (15) NOT NULL,
 PRIMARY KEY (LOGIN_VENDEDOR)
 FOREIGN KEY (LOGIN_VENDEDOR) REFERENCES VENDEDOR ON DELETE CASCADE
);
CREATE TABLE JUEGO
(
 ID_JUEGO VARCHAR2(15) NOT NULL,
 NOMBRE_JUEGO VARCHAR2(20) NOT NULL,
 PLATAFORMA VARCHAR2(20) NOT NULL, 
 GENERO VARCHAR2(20) NOT NULL,
 TIPO VARCHAR2(20) NOT NULL,
 PRECIO_COMPRA DECIMAL(3,2),
 CATEGORIA VARCHAR2 (10),
 NOVEDAD BOOLEAN,
 COMPRA BOOLEAN,
 VENTA BOOLEAN,
 PRIMARY KEY (ID_JUEGO)
);
CREATE TABLE TARIFA 
(
  ID_TARIFA VARCHAR2 (15) NOT NULL,
  PRECIO_TARIFA DECIMAL (2,2),
  CATEGORIA_TARIFA VARCHAR2 (10),
  TIEMPO_TARIFA NUMBER(4)
);
CREATE TABLE ALQUILA 
(
  LOGIN_SOCIO VARCHAR2 (15) NOT NULL,
  ID_TARIFA VARCHAR2 (15) NOT NULL,
  FECHA_ALQUILER DATETIME (6),
  PRIMARY KEY (LOGIN_SOCIO, ID_TARIFA, FECHA_ALQUILER),
  FOREIGN KEY (LOGIN_SOCIO) REFERENCES SOCIO ON DELETE CASCADE
  FOREIGN KEY (ID_TARIFA) REFERENCES TARIFA ON DELETE CASCADE 
);
CREATE TABLE COMPRA
(
  LOGIN_SOCIO VARCHAR2 (15) NOT NULL,
  ID_JUEGO VARCHAR2(15) NOT NULL,
  FECHA_COMPRA DATETIME (6),
  PRIMARY KEY (LOGIN_SOCIO, ID_JUEGO, FECHA_COMPRA),
  FOREIGN KEY (LOGIN_SOCIO) REFERENCES SOCIO ON DELETE CASCADE,
  FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO ON DELETE CASCADE
);
CREATE TABLE ASOCIADO
(
  ID_TARIFA VARCHAR2 (15) NOT NULL,
  ID_JUEGO VARCHAR2(15) NOT NULL,
  FECHA_TARIFA DATETIME (6),
  PRIMARY KEY (LOGIN_TARIFA, ID_JUEGO, FECHA_TARIFA),
  FOREIGN KEY (LOGIN_SOCIO) REFERENCES SOCIO ON DELETE CASCADE,
  FOREIGN KEY (ID_JUEGO) REFERENCES JUEGO ON DELETE CASCADE
);

/* ***********************************************/
/* 3.- Creamos los índices */
/* ***********************************************/


/* ***********************************************/
/* 4.- Creamos las vistas para nuestra temática */
/* ***********************************************/

/* ********************************************************/
/* 5.- Insertamos datos de ejemplo para todas las tablas */
/* ********************************************************/

/* *******************************************/
/* 6.- Incluímos sentencias de comprobación */
/* *******************************************/

/* ****************************************/
/* 7.- Procedimientos y Funciones PL/SQL */
/* ****************************************/

/* ***********************/
/* 8.- TRIGGERS */
/* ***********************/
  